name: Check Markdown

on:
  pull_request:
    branches:
      - '**'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Use Node from Volta
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version-file: 'package.json'
        cache: 'npm'

    - name: install dependencies
      run: npm ci

    - name: check internal markdown links
      run: npm run check-links

  markdown-spelling-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Use Node from Volta
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version-file: 'package.json'
        cache: 'npm'

    - name: install dependencies
      run: npm ci

    - name: check spelling
      run: npm run spellcheck
